FROM confluentinc/cp-kafka-connect:7.5.0
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:14.1.0
RUN confluent-hub install --no-prompt debezium/debezium-connector-mysql:2.4.2
