apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: consumerGroup
      value: "payroll-service-group"
    - name: authType
      value: "none"
    - name: disableTls
      value: "true"
    - name: initialOffset
      value: "oldest"
